# Generated by Django 5.0 on 2024-02-12 09:39

import django.core.validators
import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), main.models.validate_email])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with +44 and have 10 digits.', regex='^\\+44\\d{10}$')])),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredients', models.TextField()),
                ('dietary_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_1_name', models.CharField(max_length=50)),
                ('parent_1_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('parent_1_phone', models.CharField(max_length=10)),
                ('parent_1_address', models.CharField(max_length=100)),
                ('parent_2_name', models.CharField(max_length=50)),
                ('parent_2_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('parent_2_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with +44 and have 10 digits.', regex='^\\+44\\d{10}$')])),
                ('parent_2_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_history', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with +44 and have 10 digits.', regex='^\\+44\\d{10}$')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
        migrations.CreateModel(
            name='YearForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('students', models.ManyToManyField(to='main.student')),
            ],
        ),
    ]
