# Generated by Django 5.0 on 2024-02-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_yearform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='password2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='yearform',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
