# Generated by Django 5.0 on 2024-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parent_password1_parent_password2_student_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='parent',
            name='password1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='password2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
