# Generated by Django 5.0 on 2024-02-28 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_user_alter_parent_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reserves',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_2_phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone numbers must start with +44 and have 10 digits.', regex='^\\+44\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='password2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
